---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.13.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Homework2


<li>Create a plot using an appropriate visualization technique that best presents the <b>global pattern of the height and weight features</b> of the 2016 medal winners of the five sports.


```{python}
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
plt.style.use('ggplot')
```

```{python}
athlete_events = pd.read_csv("../Dataset/athlete_events.csv")
winners = athlete_events.dropna(subset = ["Medal"])
winners_2016 = winners[winners.Year == 2016]
top5_sports = winners_2016.Sport.value_counts()[:5].index.to_list()
winners_2016_top5 = winners_2016[winners_2016.Sport.isin(top5_sports)]
```

```{python}
winners_2016_top5.head()
```

```{python}
ax1 = sns.scatterplot(x = 'Height', y = 'Weight', data = winners_2016_top5 )
_ = ax1.set_title(label = "The pattern of the height and weight of medal winners of the five sports (2016)", 
                  fontsize = 14, 
                  fontweight = "bold",
                  pad = 20)
```

```{python}
sns.set(style = 'ticks')
ax2 = sns.jointplot(winners_2016_top5['Height'], winners_2016_top5['Weight'], kind = 'hex', color = 'g')
_ = ax2.fig.suptitle(t = "The pattern of the height and weight of medal winners of the five sports (2016)",
                     y = 1.02, 
                     fontweight = "bold")
```

```{python}
sns.set_style('white')
ax3 = sns.kdeplot(winners_2016_top5['Height'], winners_2016_top5['Weight'], shade = True)
_ = ax3.set_title(label = "The pattern of the height and weight of medal winners of the five sports (2016)", 
                  fontsize = 14, 
                  fontweight = "bold",
                  pad = 20)
```

   <li>Create a plot using an appropriate visualization technique that best presents the <b>summary statistic for the height and weight </b>of the players that won each type of medal (gold/silver/bronze) in the data.


### Summary statistic for the weight

```{python}
ax4 = sns.boxplot(x = 'Medal', y = 'Weight', data = winners_2016_top5)
_ = ax4.set_title(label = "Boxplot of the weight of medal winners of the five sports (2016)", 
                  fontsize = 14, 
                  fontweight = "bold",
                  pad = 20)
#no important information
```

```{python}
ax5 = sns.boxplot(x = 'Medal', y = 'Weight', hue= "Sex", data = winners_2016_top5)
_ = ax5.set_title(label = "Boxplot of the Weight of medal winners of the five sports (2016) split by Sex", 
                  fontsize = 14, 
                  fontweight = "bold",
                  pad = 20)
_ = plt.legend(loc='upper right')
```

```{python}
ax6 = sns.violinplot(x = 'Medal', y = 'Weight', hue= "Sex", data = winners_2016_top5)
_ = ax6.set_title(label = "Violinplot of the weight of medal winners of the five sports (2016) split by Sex", 
                  fontsize = 14, 
                  fontweight = "bold",
                  pad = 20)
```

### Summary statistic for the Height

```{python}
ax7 = sns.boxplot(x = 'Medal', y = 'Height', data = winners_2016_top5)
_ = ax7.set_title(label = "Boxplot of the Height of medal winners of the five sports (2016)", 
                  fontsize = 14, 
                  fontweight = "bold",
                  pad = 20)
#no important information
```

```{python}
ax8 = sns.boxplot(x = 'Medal', y = 'Height', hue= "Sex", data = winners_2016_top5)
_ = ax8.set_title(label = "Boxplot of the Height of medal winners of the five sports (2016) split by Sex", 
                  fontsize = 14, 
                  fontweight = "bold",
                  pad = 20)
```

```{python}
ax9 = sns.violinplot(x = 'Medal', y = 'Height', hue= "Sex", data = winners_2016_top5)
_ = ax9.set_title(label = "Violinplot of the Height of medal winners of the five sports (2016) split by Sex", 
                  fontsize = 14, 
                  fontweight = "bold",
                  pad = 20)
```

# Homework3


<ul>
    <li>Create a Plotly Express scatter plot with the x- and y-axes as year and co2 respectively. Add a box plot for the co2 values with the marginaly_y parameter.
    <li>Create a rug plot for the gdp values with the marginal_x parameter. Add the
animation parameters on the year column
    <li>Create a scatter plot with the x- and y-axes as gdp and co2 respectively.
    <li>Create a density contour with the x- and y-axes as gdp and co2 respectively.


## Prepare Data

```{python}
co2 = pd.read_csv("../Dataset/co2.csv")
gm = pd.read_csv('../Dataset/gapminder.csv')
```

```{python}
co2.head()
```

```{python}
gm.head()
```

```{python}
df_gm = gm[['Country', 'region']].drop_duplicates()
df_gm.head()
```

```{python}
df_w_regions = pd.merge(co2, df_gm, 
                        left_on = 'country', 
                        right_on = 'Country', 
                        how = 'inner')
df_w_regions.head()
```

```{python}
df_w_regions = df_w_regions.drop('Country', axis = 1)
```

```{python}
new_co2 = pd.melt(df_w_regions, 
                  id_vars = ['country', 'region'])
new_co2.head()
```

```{python}
new_co2.columns = ['country', 'region', 'year', 'co2']
df_co2 = new_co2[new_co2['year'].astype(int) > 1963].sort_values(by = ['country', 'year'])
df_co2['year'] = df_co2['year'].astype(int)
df_co2.head()
```

```{python}
df_gdp = gm[['Country', 'Year', 'gdp']]
df_gdp.columns = [x.lower() for x in df_gdp.columns]
data = pd.merge(df_co2, df_gdp, on = ['country', 'year'], how = 'left').dropna()
data.head()
```

<li>Create a Plotly Express scatter plot with the x- and y-axes as year and co2 respectively. Add a box plot for the co2 values with the marginaly_y parameter.

```{python}
import plotly.express as px
```

```{python}
len(data.country.unique())
```

```{python}
data.region.unique()
```

```{python}
fig1 = px.scatter(data, 
                 x = 'year',
                 y = 'co2',
                 hover_name = 'country',
                 color = 'region',
                 marginal_y="box")
fig1.update_xaxes(title_text='region',row=1, col=2)
fig1.update_layout(
    title={
        'text': "Scatterplot with year and co2 respectively and boxplot for the co2 values by region",
        'y':0.95,
        'x':0.45})
fig1.show()
```

 <li>Create a rug plot for the gdp values with the marginal_x parameter. Add the
animation parameters on the year column
<li>Create a scatter plot with the x- and y-axes as gdp and co2 respectively.

```{python}
fig2 = px.scatter(data, 
                 x = 'gdp',
                 y = 'co2',
                 hover_name = 'country',
                 color = 'region',
                 marginal_y="box",
                 marginal_x="rug",
                 animation_frame = 'year'
                 )
fig2.update_xaxes(title_text='region',row=1, col=2)
fig2.update_yaxes(title_text='region',row=2, col=1)
fig2.update_yaxes(title_text='co2',row=1, col=1)
fig2.update_layout(
    title={
        'text': "Scatterplot with gdp and co2 respectively and rugplot for the gdp and boxplot for co2 by region",
        'y':0.95,
        'x':0.45})
fig2.show()
```

 <li>Create a density contour with the x- and y-axes as gdp and co2 respectively.

```{python}
fig3 = px.density_contour(data, 
                 x = 'gdp',
                 y = 'co2',
                 hover_name = 'country',
                 color = 'region',
                 marginal_y="box",
                 marginal_x="rug",
                 animation_frame = 'year'
                 )
fig3.update_xaxes(title_text='region',row=1, col=2)
fig3.update_yaxes(title_text='region',row=2, col=1)
fig3.update_yaxes(title_text='co2',row=1, col=1)
fig3.update_layout(
    title={
        'text': "Density contour with gdp and co2 respectively and rugplot for the gdp and boxplot for co2 by region",
        'y':0.95,
        'x':0.45})
fig3.show()
```

```{python}

```
